// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config = {
  API: {
    GraphQL: {
      endpoint:
        "https://t4xlfuvc3fcdjmzcbs6dwfwplu.appsync-api.us-east-1.amazonaws.com/graphql",
      region: "us-east-1",
      defaultAuthMode: "apiKey",
      apiKey: "",
    },
  },
};

export default config;
